# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  
  - name: Get Core & Configure
    before: |
      # wget https://downloads.lambdatest.com/hyperexecute/windows/hyperexecute.exe
      export LT_USERNAME=himanshujlambdatest
      export LT_ACCESS_KEY=DLGw9ZAiJgjofx05nZVQ0T7GtZuCPHzX0XnEMjxivJy267p7i6
      export HYPEREXECUTE_PLATFORM="win 10"
    init: |
      echo "Performing test"
      ./hyperexecute --config yaml/win/testng_hyperexecute_autosplit_sample.yaml --download-artifacts --force-clean-artifacts
      echo "Test completion"
