# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Get Core & Configure
    before: |
      wget https://downloads.lambdatest.com/hyperexecute/linux/hyperexecute
      chmod 0777 hyperexecute
      export LT_USERNAME=himanshujlambdatest
      export LT_ACCESS_KEY=eBWZGTtxP1zhmsunJoBU5Ks0KB8bIvBaP57OtPG1lqnR7nEJwI
      export HYPEREXECUTE_PLATFORM=win10
    init: |
      echo "Performing test"
      ./hyperexecute --config yaml/win/testng_hyperexecute_autosplit_sample.yaml --download-artifacts --force-clean-artifacts
      echo "Test completion"
